# Generated by Django 5.0.8 on 2024-08-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_cols_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='col_one',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='col_three',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='col_two',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cols_heading',
        ),
    ]
