# Generated by Django 5.1.1 on 2024-09-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_background_image_alter_homepage_body'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Homepage hero section background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
